[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "npm run build --workspace=packages/types",
  "npm run build --workspace=packages/validators",
  "cd apps/api && npx prisma generate && npm run build && npx prisma db push --accept-data-loss"
]

[start]
cmd = "cd apps/api && node dist/server.js"
